site_name: Keras_genes Documentation
nav:
        - Home: index.md
        - Generator:
                Generator: generators.md
                Classification:  sparse.md
                Regression: continuous.md
        - MultiGenerator:
                Dataset: dataset.md
                MultiGenerator: multigenerator.md
        - ModelWrapper:
                Getting started: modelwrapper.md
                Advanced use: modelwrapperadvanced.md
        - Other:
                Normalization: normalization.md
                Weights: weights.md
theme: readthedocs
site_favicon: favicon.ico
