site_name: Keras_dna Documentation
nav:
        - Home: index.md
        - Generator:
                - Generator: generators.md
                - Classification:  sparse.md
                - Regression: continuous.md
        - MultiGenerator:
                - Dataset: dataset.md
                - MultiGenerator: multigenerator.md
        - ModelWrapper:
                - Introduction: modelwrapper.md
                - Advanced use: modelwrapperadvanced.md
        - Other:
                - Normalization: normalization.md
                - Weights: weights.md
        - Case study:
                - Case study: case_study.md
theme: readthedocs
site_favicon: favicon.ico
