site_name: Keras_genes Documentation
nav:
        - Home: index.md
        - Getting started::
                Guide to Generator:  generators.md
                Guide to ModelWrapper: modelwrapper.md
theme: readthedocs
site_favicon: favicon.ico
